name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install Buildozer
      run: |
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk
    
    - name: Build APK
      run: |
        buildozer init
        echo "[app]" > buildozer.spec
        echo "title = SharedNotepad" >> buildozer.spec
        echo "package.name = sharednotepad" >> buildozer.spec
        echo "package.domain = org.example" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "version = 1.0" >> buildozer.spec
        echo "requirements = python3,kivy" >> buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: shared-notepad
        path: bin/*.apk
